package com.drug.model;
// Generated Jul 30, 2016 11:09:43 AM by Hibernate Tools 5.1.0.Beta1

/**
 * PackageId generated by hbm2java
 */
public class PackageId implements java.io.Serializable {

  private String productid;
  private String ndcpackagecode;

  public PackageId() {
  }

  public PackageId(String productid, String ndcpackagecode) {
    this.productid = productid;
    this.ndcpackagecode = ndcpackagecode;
  }

  public String getProductid() {
    return this.productid;
  }

  public void setProductid(String productid) {
    this.productid = productid;
  }

  public String getNdcpackagecode() {
    return this.ndcpackagecode;
  }

  public void setNdcpackagecode(String ndcpackagecode) {
    this.ndcpackagecode = ndcpackagecode;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof PackageId))
      return false;
    PackageId castOther = (PackageId) other;

    return ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
        && castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())))
        && ((this.getNdcpackagecode() == castOther.getNdcpackagecode())
            || (this.getNdcpackagecode() != null && castOther.getNdcpackagecode() != null
                && this.getNdcpackagecode().equals(castOther.getNdcpackagecode())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
    result = 37 * result + (getNdcpackagecode() == null ? 0 : this.getNdcpackagecode().hashCode());
    return result;
  }

}
