package com.drug.model;
// Generated Jul 29, 2016 11:56:47 AM by Hibernate Tools 5.1.0.Beta1

/**
 * ProductId generated by hbm2java
 */
public class Product implements java.io.Serializable {

  private String Id;
  private String productid;
  private String productndc;
  private String producttypename;
  private String proprietaryname;
  private String proprietarynamesuffix;
  private String nonproprietaryname;
  private String dosageformname;
  private String routename;
  private String startmarketingdate;
  private String endmarketingdate;
  private String marketingcategoryname;
  private String applicationnumber;
  private String labelername;
  private String substancename;
  private String activeNumeratorStrength;
  private String activeIngredUnit;
  private String pharmClasses;
  private String deaschedule;

  public Product() {
  }

  public Product(String productid, String productndc, String producttypename, String proprietaryname,
      String proprietarynamesuffix, String nonproprietaryname, String dosageformname, String routename,
      String startmarketingdate, String endmarketingdate, String marketingcategoryname, String applicationnumber,
      String labelername, String substancename, String activeNumeratorStrength, String activeIngredUnit,
      String pharmClasses, String deaschedule) {
    this.productid = productid;
    this.productndc = productndc;
    this.producttypename = producttypename;
    this.proprietaryname = proprietaryname;
    this.proprietarynamesuffix = proprietarynamesuffix;
    this.nonproprietaryname = nonproprietaryname;
    this.dosageformname = dosageformname;
    this.routename = routename;
    this.startmarketingdate = startmarketingdate;
    this.endmarketingdate = endmarketingdate;
    this.marketingcategoryname = marketingcategoryname;
    this.applicationnumber = applicationnumber;
    this.labelername = labelername;
    this.substancename = substancename;
    this.activeNumeratorStrength = activeNumeratorStrength;
    this.activeIngredUnit = activeIngredUnit;
    this.pharmClasses = pharmClasses;
    this.deaschedule = deaschedule;
  }

  public String getId() {
    return this.productid;
  }

  public void setId(String productid) {
    this.productid = productid;
  }

  public String getProductid() {
    return this.productid;
  }

  public void setProductid(String productid) {
    this.productid = productid;
  }

  public String getProductndc() {
    return this.productndc;
  }

  public void setProductndc(String productndc) {
    this.productndc = productndc;
  }

  public String getProducttypename() {
    return this.producttypename;
  }

  public void setProducttypename(String producttypename) {
    this.producttypename = producttypename;
  }

  public String getProprietaryname() {
    return this.proprietaryname;
  }

  public void setProprietaryname(String proprietaryname) {
    this.proprietaryname = proprietaryname;
  }

  public String getProprietarynamesuffix() {
    return this.proprietarynamesuffix;
  }

  public void setProprietarynamesuffix(String proprietarynamesuffix) {
    this.proprietarynamesuffix = proprietarynamesuffix;
  }

  public String getNonproprietaryname() {
    return this.nonproprietaryname;
  }

  public void setNonproprietaryname(String nonproprietaryname) {
    this.nonproprietaryname = nonproprietaryname;
  }

  public String getDosageformname() {
    return this.dosageformname;
  }

  public void setDosageformname(String dosageformname) {
    this.dosageformname = dosageformname;
  }

  public String getRoutename() {
    return this.routename;
  }

  public void setRoutename(String routename) {
    this.routename = routename;
  }

  public String getStartmarketingdate() {
    return this.startmarketingdate;
  }

  public void setStartmarketingdate(String startmarketingdate) {
    this.startmarketingdate = startmarketingdate;
  }

  public String getEndmarketingdate() {
    return this.endmarketingdate;
  }

  public void setEndmarketingdate(String endmarketingdate) {
    this.endmarketingdate = endmarketingdate;
  }

  public String getMarketingcategoryname() {
    return this.marketingcategoryname;
  }

  public void setMarketingcategoryname(String marketingcategoryname) {
    this.marketingcategoryname = marketingcategoryname;
  }

  public String getApplicationnumber() {
    return this.applicationnumber;
  }

  public void setApplicationnumber(String applicationnumber) {
    this.applicationnumber = applicationnumber;
  }

  public String getLabelername() {
    return this.labelername;
  }

  public void setLabelername(String labelername) {
    this.labelername = labelername;
  }

  public String getSubstancename() {
    return this.substancename;
  }

  public void setSubstancename(String substancename) {
    this.substancename = substancename;
  }

  public String getActiveNumeratorStrength() {
    return this.activeNumeratorStrength;
  }

  public void setActiveNumeratorStrength(String activeNumeratorStrength) {
    this.activeNumeratorStrength = activeNumeratorStrength;
  }

  public String getActiveIngredUnit() {
    return this.activeIngredUnit;
  }

  public void setActiveIngredUnit(String activeIngredUnit) {
    this.activeIngredUnit = activeIngredUnit;
  }

  public String getPharmClasses() {
    return this.pharmClasses;
  }

  public void setPharmClasses(String pharmClasses) {
    this.pharmClasses = pharmClasses;
  }

  public String getDeaschedule() {
    return this.deaschedule;
  }

  public void setDeaschedule(String deaschedule) {
    this.deaschedule = deaschedule;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof Product))
      return false;
    Product castOther = (Product) other;

    return ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
        && castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())))
        && ((this.getProductndc() == castOther.getProductndc()) || (this.getProductndc() != null
            && castOther.getProductndc() != null && this.getProductndc().equals(castOther.getProductndc())))
        && ((this.getProducttypename() == castOther.getProducttypename())
            || (this.getProducttypename() != null && castOther.getProducttypename() != null
                && this.getProducttypename().equals(castOther.getProducttypename())))
        && ((this.getProprietaryname() == castOther.getProprietaryname())
            || (this.getProprietaryname() != null && castOther.getProprietaryname() != null
                && this.getProprietaryname().equals(castOther.getProprietaryname())))
        && ((this.getProprietarynamesuffix() == castOther.getProprietarynamesuffix())
            || (this.getProprietarynamesuffix() != null && castOther.getProprietarynamesuffix() != null
                && this.getProprietarynamesuffix().equals(castOther.getProprietarynamesuffix())))
        && ((this.getNonproprietaryname() == castOther.getNonproprietaryname())
            || (this.getNonproprietaryname() != null && castOther.getNonproprietaryname() != null
                && this.getNonproprietaryname().equals(castOther.getNonproprietaryname())))
        && ((this.getDosageformname() == castOther.getDosageformname()) || (this.getDosageformname() != null
            && castOther.getDosageformname() != null && this.getDosageformname().equals(castOther.getDosageformname())))
        && ((this.getRoutename() == castOther.getRoutename()) || (this.getRoutename() != null
            && castOther.getRoutename() != null && this.getRoutename().equals(castOther.getRoutename())))
        && ((this.getStartmarketingdate() == castOther.getStartmarketingdate())
            || (this.getStartmarketingdate() != null && castOther.getStartmarketingdate() != null
                && this.getStartmarketingdate().equals(castOther.getStartmarketingdate())))
        && ((this.getEndmarketingdate() == castOther.getEndmarketingdate())
            || (this.getEndmarketingdate() != null && castOther.getEndmarketingdate() != null
                && this.getEndmarketingdate().equals(castOther.getEndmarketingdate())))
        && ((this.getMarketingcategoryname() == castOther.getMarketingcategoryname())
            || (this.getMarketingcategoryname() != null && castOther.getMarketingcategoryname() != null
                && this.getMarketingcategoryname().equals(castOther.getMarketingcategoryname())))
        && ((this.getApplicationnumber() == castOther.getApplicationnumber())
            || (this.getApplicationnumber() != null && castOther.getApplicationnumber() != null
                && this.getApplicationnumber().equals(castOther.getApplicationnumber())))
        && ((this.getLabelername() == castOther.getLabelername()) || (this.getLabelername() != null
            && castOther.getLabelername() != null && this.getLabelername().equals(castOther.getLabelername())))
        && ((this.getSubstancename() == castOther.getSubstancename()) || (this.getSubstancename() != null
            && castOther.getSubstancename() != null && this.getSubstancename().equals(castOther.getSubstancename())))
        && ((this.getActiveNumeratorStrength() == castOther.getActiveNumeratorStrength())
            || (this.getActiveNumeratorStrength() != null && castOther.getActiveNumeratorStrength() != null
                && this.getActiveNumeratorStrength().equals(castOther.getActiveNumeratorStrength())))
        && ((this.getActiveIngredUnit() == castOther.getActiveIngredUnit())
            || (this.getActiveIngredUnit() != null && castOther.getActiveIngredUnit() != null
                && this.getActiveIngredUnit().equals(castOther.getActiveIngredUnit())))
        && ((this.getPharmClasses() == castOther.getPharmClasses()) || (this.getPharmClasses() != null
            && castOther.getPharmClasses() != null && this.getPharmClasses().equals(castOther.getPharmClasses())))
        && ((this.getDeaschedule() == castOther.getDeaschedule()) || (this.getDeaschedule() != null
            && castOther.getDeaschedule() != null && this.getDeaschedule().equals(castOther.getDeaschedule())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
    result = 37 * result + (getProductndc() == null ? 0 : this.getProductndc().hashCode());
    result = 37 * result + (getProducttypename() == null ? 0 : this.getProducttypename().hashCode());
    result = 37 * result + (getProprietaryname() == null ? 0 : this.getProprietaryname().hashCode());
    result = 37 * result + (getProprietarynamesuffix() == null ? 0 : this.getProprietarynamesuffix().hashCode());
    result = 37 * result + (getNonproprietaryname() == null ? 0 : this.getNonproprietaryname().hashCode());
    result = 37 * result + (getDosageformname() == null ? 0 : this.getDosageformname().hashCode());
    result = 37 * result + (getRoutename() == null ? 0 : this.getRoutename().hashCode());
    result = 37 * result + (getStartmarketingdate() == null ? 0 : this.getStartmarketingdate().hashCode());
    result = 37 * result + (getEndmarketingdate() == null ? 0 : this.getEndmarketingdate().hashCode());
    result = 37 * result + (getMarketingcategoryname() == null ? 0 : this.getMarketingcategoryname().hashCode());
    result = 37 * result + (getApplicationnumber() == null ? 0 : this.getApplicationnumber().hashCode());
    result = 37 * result + (getLabelername() == null ? 0 : this.getLabelername().hashCode());
    result = 37 * result + (getSubstancename() == null ? 0 : this.getSubstancename().hashCode());
    result = 37 * result + (getActiveNumeratorStrength() == null ? 0 : this.getActiveNumeratorStrength().hashCode());
    result = 37 * result + (getActiveIngredUnit() == null ? 0 : this.getActiveIngredUnit().hashCode());
    result = 37 * result + (getPharmClasses() == null ? 0 : this.getPharmClasses().hashCode());
    result = 37 * result + (getDeaschedule() == null ? 0 : this.getDeaschedule().hashCode());
    return result;
  }

}
